version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/test"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/src"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
