# TODO: move all of this into separate actions (warriors-life/test-code-action, warriors-life/test-image-action, warriors-life/build-image-action, warriors-life/push-image-action)
# TODO: cache actions/checkout's output
# TODO: use SARIF and github/codeql-action/upload-sarif when we'll move to GitHub Advanced Security

name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'release'
      - 'dev'
  schedule:
    - cron: '30 1 * * 6' # Weekly on Saturdays

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  NODE_ENV: ${{ (github.ref == 'ref/heads/dev' || github.base_ref == 'ref/heads/dev') && 'development' || 'release' }}

permissions: {}

jobs:
  hadolint:
    if: "!contains(github.repository, '.warriors-life-template')"
    name: Lint Dockerfile with Hadolint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
      - name: Checkout # TODO: too heavy for checking out only one file
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          persist-credentials: false
      - name: Lint
        uses: hadolint/hadolint-action@4b5806eb9c6bee4954fc0e0cc3ad6175fc9782c1
        with:
          dockerfile: src/Dockerfile
          failure-threshold: style

  scorecard:
    if: "!contains(github.repository, '.warriors-life-template')"
    name: Check supply chain with Scorecard
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            api.osv.dev:443
            auth.docker.io:443
            bestpractices.coreinfrastructure.org:443
            github.com:443
            index.docker.io:443
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          persist-credentials: false
      # TODO: disabled until GraphQL will start to support fine-grained tokens
      # - name: Run analysis
        # uses: ossf/scorecard-action@99c53751e09b9529366343771cc321ec74e9bd3d
        # with:
          # results_file: results.sarif
          # results_format: sarif
          # repo_token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Upload output
        # uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        # with:
          # name: Scorecard output
          # path: results.sarif

  metadata:
    if: "!contains(github.repository, '.warriors-life-template')"
    name: Get Docker image metadata
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=sha,prefix={{branch}}-
            type=schedule,pattern=weekly

  build:
    needs: metadata
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            auth.docker.io:443
            dl-cdn.alpinelinux.org:443
            github.com:443
            production.cloudflare.docker.com:443
            registry-1.docker.io:443
            docker.io:443
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          persist-credentials: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325
        with:
          version: https://github.com/docker/buildx.git#ed00243a0ce2a0aee75311b06e32d33b44729689
      - name: Build
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          context: src
          tags: ${{ env.IMAGE_NAME }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/image.tar
          labels: ${{ needs.metadata.outputs.labels }}
      - name: Upload Docker image
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: Docker image
          path: /tmp/image.tar

  snyk:
    needs: build
    name: Check Docker image for vulnerabilities with Snyk
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.snyk.io:443
      - name: Download Docker image
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: Docker image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/image.tar
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@7fad562681122205233d1242c3bb39598c5393da
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.IMAGE_NAME }}:test

  push:
    if: github.event_name != 'pull_request'
    needs: [hadolint, scorecard, snyk, metadata, test-nginx, test-gixy]
    name: Push Docker image to the Container registry (GitHub Packages)
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            ghcr.io:443
      - name: Download Docker image
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: Docker image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/image.tar
      - name: Log in to the Container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag Docker image properly
        run: |
          while IFS= read -r tag; do
            echo "Tagging image $tag"
            docker tag ${{ env.IMAGE_NAME }}:test "$tag"
          done <<< "${{ needs.metadata.outputs.tags }}"
      - name: Push Docker image
        run: docker push -a ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} # TODO: change this hack when https://github.com/docker/build-push-action/issues/17 will be truly fixed

  test-nginx:
    needs: build
    name: Test Nginx configuration
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: test
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          persist-credentials: false
      - name: Download Docker image
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: Docker image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/image.tar
      - name: Generate SSL certificates
        run: |
          openssl req -x509 -config ssl-config/openssl-ca.conf -out ssl/warriorslife.site.fullchain.crt -keyout ssl-config/ca.key -noenc
          openssl req -CA ssl/warriorslife.site.fullchain.crt -CAkey ssl-config/ca.key -config ssl-config/openssl-cert.conf -out ssl/warriorslife.site.crt -keyout ssl/warriorslife.site.key -noenc
      - name: Run nginx -t
        run: docker run --rm --env-file test.env --mount type=bind,src="$(pwd)"/ssl,dst=/ssl,ro ${{ env.IMAGE_NAME }}:test nginx -t

  test-gixy:
    needs: build
    name: Test Nginx configuration with Gixy
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: test
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            auth.docker.io:443
            github.com:443
            production.cloudflare.docker.com:443
            registry-1.docker.io:443
      - name: Checkout # TODO: too heavy for checking out only one file
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          persist-credentials: false
      - name: Download Docker image
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: Docker image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/image.tar
      - name: Run Gixy test
        run: |
          docker run --rm --env-file test.env --mount type=volume,src=nginx-conf,dst=/etc/nginx ${{ env.IMAGE_NAME }}:test nginx -v
          docker run --rm --mount type=volume,src=nginx-conf,dst=/etc/nginx,ro getpagespeed/gixy:v0.1.22@sha256:3721944f812a94f4de0f92e0e31d938381abd6fed1f8f64a5cd7abddf063012b