# TODO: make test-nginx and test-gixy based on a separate action

name: Build

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - 'release/?*'
      - 'dev'
  schedule:
    - cron: '30 1 * * 6' # Weekly on Saturdays

permissions: {}

jobs:
  call-workflow:
    if: "!contains(github.repository, '.warriors-life-template')"
    uses: warriors-life/.warriors-life-workflows/.github/workflows/build-docker.yml@dev
    with:
      image-name: ${{ github.repository }}
      node-code-pre-test: |
        export $(xargs < test.env) && cat test.env >> $GITHUB_ENV
        openssl req -x509 -config ssl-config/openssl-ca.conf -out server$NGINX_TRUSTED_CERTS -keyout ssl-config/ca.key -noenc
        openssl req -config ssl-config/openssl-cert.conf -CA server$NGINX_TRUSTED_CERTS -CAkey ssl-config/ca.key -out server$NGINX_CERT -keyout server$NGINX_CERT_KEY -noenc
        gzip -k server/static/*.{css,csv,html,ico,js,json,svg,txt,wasm,webmanifest}
        cd server && docker-compose up -d
    secrets: inherit
    permissions:
      security-events: write
      packages: write
      actions: read
      contents: read
      issues: read
      pull-requests: read

  test-nginx:
    needs: call-workflow
    name: Test Nginx configuration
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: test
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          persist-credentials: false
      - name: Download Docker image
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: Docker image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/image.tar
      - name: Generate SSL certificates
        run: |
          export $(xargs < test.env)
          openssl req -x509 -config ssl-config/openssl-ca.conf -out server$NGINX_TRUSTED_CERTS -keyout ssl-config/ca.key -noenc
          openssl req -config ssl-config/openssl-cert.conf -CA server$NGINX_TRUSTED_CERTS -CAkey ssl-config/ca.key -out server$NGINX_CERT -keyout server$NGINX_CERT_KEY -noenc
      - name: Run nginx -t
        run: docker run --rm --env-file test.env --mount type=bind,src="$(pwd)"/server/ssl,dst=/ssl,ro ${{ needs.call-workflow.outputs.test-tag }} nginx -t

  test-gixy:
    needs: call-workflow
    name: Test Nginx configuration with Gixy
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: test
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            registry-1.docker.io:443
            auth.docker.io:443
            production.cloudflare.docker.com:443
      - name: Checkout # TODO: too heavy for checking out only one file
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          persist-credentials: false
      - name: Download Docker image
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: Docker image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/image.tar
      - name: Run Gixy test
        run: |
          docker run --rm --env-file test.env --mount type=volume,src=nginx-conf,dst=/etc/nginx ${{ needs.call-workflow.outputs.test-tag }} nginx -v
          docker run --rm --mount type=volume,src=nginx-conf,dst=/etc/nginx,ro getpagespeed/gixy:v0.1.22@sha256:3721944f812a94f4de0f92e0e31d938381abd6fed1f8f64a5cd7abddf063012b
