# TODO: use SARIF and github/codeql-action/upload-sarif when we move to GitHub Advanced Security

name: Supply-chain security

on:
  # Only the default branch is supported.
  branch_protection_rule:
  schedule:
    # Weekly on Saturdays.
    - cron: '30 1 * * 6'
  push:
    branches:
      - 'release'
      - 'dev'

permissions: {}

jobs:
  scorecard-analysis:
    if: "!contains(github.repository, 'repository-template')"

    name: Scorecard analysis

    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@0a5820a2ec510d2521c1715d24860fc8cd06400a
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            api.osv.dev:443
            auth.docker.io:443
            bestpractices.coreinfrastructure.org:443
            github.com:443
            index.docker.io:443

      - name: Checkout code
        uses: actions/checkout@bf085276cecdb0cc76fbbe0687a5a0e786646936
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@420fff2430efabf8e215ab219e0efb528410d598
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: Scorecard output
          path: results.sarif